# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20160930_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
