# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20161005_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
