# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 21:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
