# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20161005_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.IntegerField(blank=True, editable=False, unique=True),
        ),
    ]
