# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20161012_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='pois',
        ),
    ]
