# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_remove_place_pois'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointOfInterest',
        ),
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
