# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20161007_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
