# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20161114_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
