# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_place_pois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='pois',
            field=models.ManyToManyField(blank=True, to='places.PointOfInterest'),
        ),
    ]
