# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20161125_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
