# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 14:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20161125_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
