# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkintype',
            name='id',
        ),
        migrations.AddField(
            model_name='checkintype',
            name='alias',
            field=models.CharField(default=1, max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
