# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='app',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='updated_at',
        ),
    ]
