# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_auto_20160927_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkintype',
            name='alias',
        ),
        migrations.AddField(
            model_name='checkintype',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
