# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20160930_2103'),
        ('presence', '0003_auto_20160927_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
            preserve_default=False,
        ),
    ]
