# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0002_auto_20160930_2103'),
        ('presence', '0004_checkin_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='checkintype',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='checkin_type',
        ),
        migrations.DeleteModel(
            name='CheckinType',
        ),
    ]
