# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0007_auto_20161103_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
