# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0008_auto_20161103_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
