# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0011_auto_20161104_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presence.Session'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presence.Session'),
        ),
    ]
